/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Maxwell design tokens — Syntropy Red
        cherry: {
          DEFAULT: '#B8333E',
          hover: '#D64550',
          light: 'rgba(184, 51, 62, 0.12)',
          50: 'rgba(184, 51, 62, 0.06)',
          100: 'rgba(184, 51, 62, 0.12)',
          200: 'rgba(184, 51, 62, 0.25)',
          300: '#B8333E',
          400: '#D64550',
          500: '#B8333E',
          600: '#D64550',
          700: '#8A1E26',
        },
        emerald: {
          DEFAULT: '#10B981',
          light: '#ECFDF5',
        },
        amber: {
          DEFAULT: '#F59E0B',
          light: '#FFFBEB',
        },
        slate: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          400: '#94A3B8',
          500: '#64748B',
          900: '#1E293B',
        },
        maxwell: {
          primary: '#B8333E',
          'primary-hover': '#D64550',
          'primary-light': 'rgba(184, 51, 62, 0.12)',
          secondary: '#10B981',
          'secondary-light': 'rgba(16, 185, 129, 0.12)',
          accent: '#F59E0B',
          'accent-light': 'rgba(245, 158, 11, 0.12)',
          background: '#0A0A0F',
          surface: '#141419',
          'surface-raised': '#1E1E26',
          'text-primary': '#F0F0F5',
          'text-secondary': '#8A8A96',
          'text-tertiary': '#5A5A66',
          border: '#2A2A35',
          'border-subtle': '#1E1E26',
          danger: '#DC2626',
          'danger-light': 'rgba(220, 38, 38, 0.12)',
        },
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        'radius-sm': '6px',
        'radius-md': '8px',
        'radius-lg': '12px',
        'radius-xl': '16px',
        'radius-2xl': '20px',
        'radius-full': '9999px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'sm': '0 1px 2px rgba(0,0,0,0.04)',
        'md': '0 2px 8px rgba(0,0,0,0.06)',
        'lg': '0 4px 16px rgba(0,0,0,0.08)',
        'xl': '0 8px 32px rgba(0,0,0,0.10)',
        'upload': '0 0 0 3px rgba(184, 51, 62, 0.20)',
        'toast': '0 4px 12px rgba(0,0,0,0.12)',
      },
      fontFamily: {
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'h1': ['3.5rem', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'h2': ['1.25rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['1rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body': ['0.875rem', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'caption': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'button': ['0.875rem', { lineHeight: '1', letterSpacing: '0', fontWeight: '600' }],
        'nav': ['0.875rem', { lineHeight: '1', letterSpacing: '0', fontWeight: '500' }],
        'search': ['1rem', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'badge': ['0.6875rem', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'empty-title': ['1.125rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'empty-body': ['0.875rem', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      maxWidth: {
        'container': '1200px',
        'content': '720px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "scan-sweep": {
          "0%": { transform: "translateX(-100%)", opacity: "0.6" },
          "50%": { opacity: "1" },
          "100%": { transform: "translateX(400%)", opacity: "0.6" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "pulse-border": {
          "0%, 100%": { boxShadow: "0 0 0 3px rgba(184, 51, 62, 0.20)" },
          "50%": { boxShadow: "0 0 0 6px rgba(184, 51, 62, 0.10), 0 0 0 3px rgba(184, 51, 62, 0.20)" },
        },
        "spinner": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "bounce-in": {
          "0%": { transform: "scale(0)" },
          "50%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "scan-sweep": "scan-sweep 2s cubic-bezier(0.65, 0, 0.35, 1) infinite",
        "float": "float 3s ease-in-out infinite",
        "pulse-border": "pulse-border 1.2s ease-in-out infinite",
        "spinner": "spinner 0.8s linear infinite",
        "bounce-in": "bounce-in 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
